### ISSUE TITLE
Couldn't start application

### ISSUE THREAD

**Issue by walnads** [AY1920S1-CS2103T-W12-1/main#252]
Hi, I couldn't start up your application during the PE Dry Run just now. Here's the error message that I received!

![image](https://user-images.githubusercontent.com/18460838/68023287-b8378c00-fce1-11e9-88c1-67b8a7eac03e.png)
![image](https://user-images.githubusercontent.com/18460838/68023296-c38ab780-fce1-11e9-97e8-4fe58ce6f5e0.png)

**Comment by marqueurs404** [comment]
I have encountered the same situation as well - could not start up your team's application due to the same error.
